version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8443:8080"
        environment:
            DB_HOST: db
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/auth-service
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: root
            SPRING_PROFILES_ACTIVE: docker
        networks:
            - my-network

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: auth-service
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - my-network

volumes:
    postgres_data:

networks:
    my-network:
        driver: bridge
