spring:
    application:
        name: AuthService

    datasource:
        url: jdbc:postgresql://db:5432/auth-service
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false

security:
    jwt:
      secret: verysecretkeyomgdonttellanybody
      lifetime: 10d