create table users
(
    id       bigint generated by default as identity primary key,
    name     varchar(48) not null,
    surname  varchar(48) not null,
    password varchar(60) not null,
    email    varchar(64) not null unique
);